<?php
/**
 * Created by PhpStorm.
 * User: neovs
 * Date: 25.08.20
 * Time: 2:07
 */

$root_dir = 'engine';
$dir = explode($root_dir, __DIR__);
define('PATH', $dir[0] . $root_dir . '/');
$autoconfig_vars = [];
$admin_config_vars = [];
$site_config = [];
autoconfig_reload();
admin_config_reload();


function autoconfig_reset()
{
    // echo "AAAA".PATH;
    $auto_config = [';HPBE_DAO;<br> <H1>403 forbidden.</H1><?php http_response_code(403); die();?>',
        '; =================== DO NOT EDIT THIS FILE. IT WAS GENERATED AUTOMATICALLY!!! ==================== ',
        ''];
    //$auto_config = file(__DIR__."/engine/config/automatic_config.php");
    // $auto_config[] = '$initial_configuration_call_time='.time().';';
    $fp = fopen(PATH . "config/automatic_config.php", "wt");
    flock($fp, LOCK_EX); // Блокирование файла для записи
    if ($fp === false) return false;
    fputs($fp, implode("\n", $auto_config));
    flock($fp, LOCK_UN); // Снятие блокировки
    return fclose($fp);
}

function admin_config_reset()
{
    // echo "AAAA".PATH;
    $admin_config = ['HPBE_DAO<br><H1>403 forbidden.</H1> <?php http_response_code(403); die(); ?>',
        '; =================== DO NOT EDIT THIS FILE. IT WAS GENERATED AUTOMATICALLY!!! ==================== ',
        '#'];
    //$auto_config = file(__DIR__."/engine/config/automatic_config.php");
    // $auto_config[] = '$initial_configuration_call_time='.time().';';
    $fp = fopen(PATH . "config/admin_panel_autoconfig.php", "wt");
    flock($fp, LOCK_EX); // Блокирование файла для записи
    if ($fp === false) return false;
    fputs($fp, implode("\n", $admin_config));
    flock($fp, LOCK_UN); // Снятие блокировки
    return fclose($fp);
}

function siteconfig_add($name, $value, $update_immediately = true)
{
    global $site_config;
    $site_config[$name] = $value;
    if ($update_immediately) return siteconfig_write();
    return true;
}

function siteconfig_remove($name, $update_immediately = true)
{
    global $site_config;
    unset($site_config[$name]);
    if ($update_immediately) return siteconfig_write();
    return true;
}

function siteconfig_get($name)
{
    global $site_config;
    if (isset($site_config[$name])) {
        return $site_config[$name];
    } else {
        return null;
    }
}

function autoconfig_add($name, $value)
{
    global $autoconfig_vars;
    $autoconfig_vars[$name] = (string)$value;
    // autoconfig_write();
}

function autoconfig_remove($name)
{
    global $autoconfig_vars;
    unset($autoconfig_vars[$name]);
}

/*function admin_config_add($name, $value) {
    global $admin_config_vars;
    $admin_config_vars[$name] = (string) $value;
    // admin_config_write();
}*/

function autoconfig_get($name)
{
    global $autoconfig_vars;
    if (isset($autoconfig_vars[$name])) {
        return $autoconfig_vars[$name];
    } else {
        return null;
    }
}

/*
function admin_config_get($name) {
    global $admin_config_vars;
    if (isset($admin_config_vars[$name])) {
        return $admin_config_vars[$name];
    } else {
        return null;
    }
}*/

function autoconfig_write()
{
    // if (!autoconfig_reset()) return false;
    $auto_config_file_content = [';HPBE_DAO;<br> <H1>403 forbidden.</H1><?php http_response_code(403); die();?>',
        '; =================== DO NOT EDIT THIS FILE. IT WAS GENERATED AUTOMATICALLY!!! ==================== ',
        ''];
    //['<?php',
    // '/** =================== DO NOT EDIT THIS FILE. IT WAS GENERATED AUTOMATICALLY!!! ==================== */',
    //  '', 'return array('];*/
    global $autoconfig_vars;
    // var_dump($autoconfig_vars);
    if (isset($autoconfig_vars)) {

        foreach ($autoconfig_vars as $var_name => $var_value) {
            $auto_config_file_content[] = $var_name . '=' . $var_value;
        }
    }
    $fp = fopen(PATH . "config/automatic_config.php", "wt");
    flock($fp, LOCK_EX); // Снятие блокировки
    if ($fp === false) return false;
    fputs($fp, implode("\n", $auto_config_file_content));
    flock($fp, LOCK_UN); // Снятие блокировки

    return fclose($fp);
}

function admin_config_write()
{
    // if (!autoconfig_reset()) return false;
    $admin_config_file_content = ['HPBE_DAO<br><H1>401 forbidden.</H1> <?php http_response_code(401); die(); ?>',
        '; =================== DO NOT EDIT THIS FILE. IT WAS GENERATED AUTOMATICALLY!!! ==================== ',
        '#'];
    //['<?php',
    // '/** =================== DO NOT EDIT THIS FILE. IT WAS GENERATED AUTOMATICALLY!!! ==================== */',
    //  '', 'return array('];*/
    global $admin_config_vars;
    // var_dump($autoconfig_vars);
    if (isset($admin_config_vars)) {
        $admin_config_file_content[] = json_encode($admin_config_vars);
    }
    $fp = fopen(PATH . "config/admin_panel_autoconfig.php", "wt");
    flock($fp, LOCK_EX); // Снятие блокировки
    if ($fp === false) return false;
    fputs($fp, implode("\n", $admin_config_file_content));
    flock($fp, LOCK_UN); // Снятие блокировки

    return fclose($fp);
}

function siteconfig_write()
{
    global $table_siteConfig;
    global $site_config;
    if (!$table_siteConfig->loadFromDatabaseAll()) {
        addErrorToLog("Site config write function", "10-1: Error config table export");
        return false;
    } else {
        foreach ($table_siteConfig->tableRecords as $record) {
            $table_siteConfig->deleteRecord('id', $record["id"]);
        }
        foreach ($site_config as $item_key => $item) {
            $table_siteConfig->addNewRecord(['key' => $item_key, 'value' => $item]);
        }
        return $table_siteConfig->applyChanges() && siteconfig_reload();

    }
}

function siteconfig_reload()
{
    if (autoconfig_get("core_configured") !== null) {
        global $table_siteConfig;
        global $site_config;
        if (!$table_siteConfig->loadFromDatabaseAll()) {
            addErrorToLog("Site config db loader", "10: Error config table import");
            return false;
        } else {
            $site_config = [];
            foreach ($table_siteConfig->tableRecords as $record) {
                $site_config[$record["key"]] = $record["value"];
            }
            return true;
        }
    } else return false;
}

function autoconfig_reload()
{
    // write_ini_file();
    if (file_exists(PATH . "config/automatic_config.php")) {
        global $autoconfig_vars;
        $autoconfig_vars = parse_ini_file(PATH . "config/automatic_config.php"); //include(PATH."config/automatic_config.php");
        return true;
    } else return autoconfig_reset();
}

function admin_config_reload()
{
    if (file_exists(PATH . "config/admin_panel_autoconfig.php")) {
        global $admin_config_vars;
        $admin_config_vars = json_decode(explode('#', file_get_contents(PATH . "config/admin_panel_autoconfig.php"))[1]); //include(PATH."config/automatic_config.php");
        return true;
    } else return admin_config_reset();
}


/* =====================SERVICE; DO NOT CHANGE OR DELETE===================================*/
$engine_autoconfig_module_loaded = 1; //DO NOT CHANGE